version: "3.7"

services:
  server:
    image: lnmarkets/nostr-rs-relay:0.7.16@sha256:3e5f0dbb3d45c701fbe06b7d2deadf6694f3231ec2d79a9bc1932ca80d153a9f
    restart: on-failure
    volumes:
      - ${PWD}/data/relay/config.toml:/home/.nostr-rs-relay/config.toml
      - ${PWD}/data/relay/db:/home/.nostr-rs-relay/db

  web:
    image: getumbrel/umbrel-nostr-relay
    build: .
    user: "1000:1000"
    restart: on-failure
    environment:
      RELAY_HOST: "server"
      RELAY_PORT: "8080"
    ports:
      - 3000:3000