version: "3.7"

services:
  server:
    image: lnmarkets/nostr-rs-relay:0.7.16@sha256:3e5f0dbb3d45c701fbe06b7d2deadf6694f3231ec2d79a9bc1932ca80d153a9f
    restart: on-failure
    volumes:
      - ${PWD}/data/relay/config.toml:/home/.nostr-rs-relay/config.toml
      - ${PWD}/data/relay/db:/home/.nostr-rs-relay/db

  web:
    build: .
    user: "1000:1000"
    restart: on-failure

  caddy:
    image: caddy:2.6.2@sha256:16f4d944907ac8adc93e11df3e4d1b8405d42e4f45e6bc1aae4eb1119552ee79
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:8080